services:
    server:
        build: ./8080
        container_name: server
        environment:
        - SERVER_PORT=8080
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/satellite_db
        - SPRING_KAFKA_BOOTSTRAP_SERVICES=kafka:9093
        - SPRING_DATA_REDIS_HOST=redis
        - SPRING_DATA_REDIS_PORT=6379
        ports:
        - "3030:8080"
        networks:
        - space-net
        depends_on:
            - db
            - redis
    mission-service:
        build: ./8081
        container_name: mission-service
        depends_on:
        - server
        environment:
        - SERVER_PORT=8081
        - SERVER_URL=http://server:8080
        ports:
        - "3031:8081"
        networks:
        - space-net
    telemetry-service:
        build: ./9091
        container_name: telemetry_service
        environment:
        - SERVER_PORT=8082
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/satellite_db
        ports:
        - "3032:8082"
        - "9091:9091"
        networks:
        - space-net
    db:
        image: postgres:16-alpine
        container_name: postgres-db
        environment:
        - POSTGRES_DB=satellite_db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        ports:
        - "5431:5432"
        networks:
        - space-net
        volumes:
        - pgdata:/var/lib/postgresql/data
    kafka:
        image: apache/kafka:latest
        container_name: kafka
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_PROCESS_ROLES: broker, controller
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094,EXTERNAL://0.0.0.0:29093
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,EXTERNAL://localhost:29093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_INNER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9094
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_NUM_PARTITIONS: 3
        ports:
            - "9093:9093"
            - "29093:29093"
        volumes:
            - ./data/kafka:/tmp/kraft-combined-logs
        networks:
            - space-net
    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        container_name: kafka-ui
        ports:
            - "8085:8080"
        environment:
            KAFKA_CLUSTERS_0_NAME: local
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
        depends_on:
            - kafka
        networks:
            - space-net
    redis:
        image: redis:7-alpine
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - space-net
        command: redis-server --appendonly yes
        volumes:
            - redis-data:/data
        restart: unless-stopped

networks:
    space-net:
        driver: bridge

volumes:
    pgdata:
    redis-data: