services:
    db:
        image: postgres:16-alpine
        container_name: postgres-db
        environment:
        - POSTGRES_DB=satellite_db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        ports:
        - "5431:5432"
        networks:
        - space-net
        volumes:
        - pgdata:/var/lib/postgresql/data

networks:
    space-net:
        driver: bridge

volumes:
    pgdata: