services:
    server:
        build: ./8080
        container_name: server
        environment:
        - SERVER_PORT=8080
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/satellite_db
        ports:
        - "3030:8080"
        networks:
        - space-net
    mission-service:
        build: ./8081
        container_name: mission-service
        depends_on:
        - server
        environment:
        - SERVER_PORT=8081
        - SERVER_URL=http://server:8080
        ports:
        - "3031:8081"
        networks:
        - space-net
    db:
        image: postgres:16-alpine
        container_name: postgres-db
        environment:
        - POSTGRES_DB=satellite_db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        ports:
        - "5431:5432"
        networks:
        - space-net
        volumes:
        - pgdata:/var/lib/postgresql/data

networks:
    space-net:
        driver: bridge

volumes:
    pgdata: