server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5431/satellite_db}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVICES:localhost:29093}
    properties:
      security.protocol: PLAINTEXT
    admin:
      auto-create-topics: true
    consumer:
      group-id: kpo
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.sputnik_onegina,java.util,java.lang"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cache:
    type: redis
    redis:
      time-to-live: 10m
      cache-null-values: false
      key-prefix: "satellite-server:"
      use-key-prefix: true
  redis:
    host: ${SPRING_DATA_REDIS_HOST:localhost}
    port: ${SPRING_DATA_REDIS_PORT:6379}
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 8
        time-between-eviction-runs: 10s

grpc:
    client:
        telemetry-service:
            address: static://telemtetry-service:9091
            negotiationType: plaintext
            enable-keep-alive: true
            keep-alive-time: 30s
            keep-alive-timeout: 5s
